config/routes.rb
FeedEngine::Application.routes.draw do

  devise_for(:users)
  
  resources :users do 
    member { get 'profile'}
  end

  get "home/index"

  get "/:feed/posts/:id/add_points" => 'posts#add_points', as: 'add_points_feed_post'
  get "/:feed/posts/:id/refeed" => 'posts#refeed', as: 'refeed_feed_post'
  post "/:feed/posts" => 'posts#create', as: 'feed_posts'
  get "/:feed/ask_for_access" => 'feeds#ask_for_access', as: 'ask_for_access_feed'
  get "/:feed/visibility" => 'feeds#visibility', as: "visibility_feed"
  post "/:feed/visibility/:user_id" => 'feeds#approve_access', as: "approve_access_feed"
  get "/:feed/visibility/toggle" => 'feeds#toggle_visibility', as: "toggle_visibility_feed"
  get "/:feed/services" => 'feeds#services', as: "services_feed"
  post "/:feed/add_service" => 'feeds#add_service', as: 'add_service_feed'
  get "/:feed/subscribe" => "feeds#subscribe", as: "subscribe_feed"
  get "/:feed" => 'feeds#index', as: 'feed'
  
  root :to => "home#index"

  

end

app/models/allowed_users_feeds.rb
class AllowedUsersFeeds < ActiveRecord::Base
  belongs_to :feed
  belongs_to :allowed_user, class_name: 'User', foreign_key: 'user_id'
end

app/models/concerns/lockable.rb
module Lockable

  def self.included receiver
    receiver.instance_eval do 
      extend ClassMethods
      include InstanceMethods
      has_many :allowed_users_feeds, class_name: 'AllowedUsersFeeds'
      has_many :allowed_users, through: :allowed_users_feeds, after_add: :mark_change 

      after_create :allow_owner 
    end
  end

  module InstanceMethods

    def mark_change user
      @changed_attributes[:allowed_users] ||= []
      @changed_attributes[:allowed_users] += [user]
    end

    def allow? user
      public? || allowed_users.where(id: user.id).exists?
    end

    def allow user
      self.allowed_users << user
      self
    end

    def allow_owner
      allowed_users << owner
    end

    def lock
      self.public = false
      save
      self
    end
  end

  module ClassMethods
    def lock feed
      feed.lock
    end
  end
end

app/models/concerns/messengable.rb
module Messengable

  def self.included receiver
    receiver.instance_eval do 
      has_many :messages,  as: :sender
      has_many :inbox, as: :receiver, class_name: 'Message'
    end
  end
end

app/models/feed.rb
class Feed < ActiveRecord::Base

  include Lockable
  include Subscribed

  belongs_to :user
  alias_attribute :owner, :user

  has_many :feeds_posts, class_name: 'FeedsPosts'
  has_many :posts, ->{ order("created_at DESC")}, through: :feeds_posts

  def total_points
    posts.sum(:points)
  end
end

app/models/feed_observer.rb
class FeedObserver < ActiveRecord::Observer

  def before_save feed
    if users =  feed.changes[:allowed_users].try(:first)
      feed.owner.inbox.access_pleaders(users).delete_all
    end
  end
end

app/models/feeds_posts.rb
class FeedsPosts < ActiveRecord::Base
  belongs_to :feed
  belongs_to :post
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, polymorphic: true
  belongs_to :receiver, polymorphic: true

  scope :access_requests, ->{ where(message_type: 'access_request')}

  ## TODO: this scope stinks, but alternative is to loop over every record. Maybe just not allow arrays?
  scope :access_pleaders, ->(sender){ senders = Array(sender);
                       access_requests.where(sender_id: senders.map(&:id), 
                        sender_type: senders.first.class) }
end

app/models/photo_post.rb
class PhotoPost < Post
  alias_attribute :photo, :content

  validates_length_of :description, maximum: 256

  def render_content template
    template.render 'posts/photo', photo_url: photo
  end

  def to_partial_path
   'posts/post' 
  end
end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :feeds_posts, class_name: 'FeedsPosts'
  has_many :feeds, through: :feeds_posts 

  paginates_per 10

  validates_length_of :description, maximum: 512

  def render_content template
    nil
  end

  def add_points
    self.points+=1
  end

  def user
    main_feed.user
  end

  def main_feed
    feeds.first
  end
end

app/models/subscribed_feed.rb
class SubscribedFeed < ActiveRecord::Base
  belongs_to :subscribent, polymorphic: true

  def self.posts
    all.to_a.reduce([]) do |total_posts, subscription|
      total_posts +=Service.create( 
        subscription.service, subscription.identifier 
        ).posts
    end
  end

  def self.list
    all.to_a.collect{|sf| sf.identifier}
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  include Messengable

  has_many :feeds
  has_many :posts, through: :feeds

  after_create :create_feed

  def main_feed
    feeds.first
  end

  def add_to_main_feed post
    main_feed.posts << post
  end

  private 

  def create_feed
    feeds.create(subdomain: nick.downcase)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# Prevent CSRF attacks by raising an exception.
# For APIs, you may want to use :null_session instead.
protect_from_forgery with: :exception

private

def subdomain
  # request.subdomain.downcase
  params[:feed]
end

def current_feed
  @feed ||= Feed.where(subdomain: subdomain).first
end

helper_method :current_feed

def subdomain_holder
  @subdomain_holder ||= current_feed.owner
end

def after_sign_in_path_for user
  profile_user_path(user)
end

def render_404
  respond_to do |format|
    format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
    format.xml  { head :not_found }
    format.any  { head :not_found }
  end
end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :new_feed
  before_action :private_feed_lock, except: [:ask_for_access]

  def index
    @posts = current_feed.all_posts
  end

  def add_service
    if params[:add] == 'false'
      current_feed.unsubscribe :twitter, params[:twitter_id]
    else
      current_feed.subscribe :twitter, params[:twitter_id]
    end
    redirect_to :back
  end

  def subscribe
    redirect_to :back, if SubscriptionService.create user: current_user, feed: current_feed
      { :notice => "Successfully subscribed to #{current_feed.subdomain}"}
    else
      { :error => "Something went wrong"}
    end
  end

  def approve_access
    user = User.find(params[:user_id])
    current_feed.allow(user).save
    redirect_to :back
  end

  def toggle_visibility
    current_feed.toggle(:public).save
    redirect_to :back
  end

  def ask_for_access
    FeedManager.ask_for_access(current_user, current_feed)
    redirect_to :back
  end

  private

  def private_feed_lock
    unless current_feed.allow?(current_user)
      render 'not_allowed'
    end
  end

  def new_feed
    unless current_feed
      redirect_to root_url
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
   @feeds = Feed.pluck(:subdomain) 
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :authenticate_user!, except: [:refeed]

  def add_points
    post = Post.find(params[:id])
    post.add_points
    post.save
    redirect_to :back
  end

  def create
    current_feed.posts.create(post_params)
    redirect_to :back
  end

  def refeed
    post = Post.find(params[:id])
    current_user.add_to_main_feed post
    redirect_to :back
  end

  private 

  def post_params
    if params.key? :post
      params.require(:post).permit(:title, :description)
    elsif params.key? :photo_post
      params.require(:photo_post).permit(:photo, :title, :description, :type)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
   @user = User.where(id: params[:id]).first || render_404
  end

  def profile
    @user = User.where(id: params[:id]).first || render_404
  end

  def update
  end

  def create
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/_forms.html.haml
.forms
  = link_to 'Photos', '#'
  .tabs
    .photo_form.tab
      Photo post
    .normal_form.tab
      Normal post
  .photo_form.form
    = render 'posts/photo_form', feed: current_feed, post: PhotoPost.new
  .normal_form.form
    = render 'posts/form', feed: current_feed, post: Post.new

app/views/feeds/index.html.haml
.feed
  = "Total points #{current_feed.total_points}"
  = @feed.user.nick
  = link_to "Visibility", visibility_feed_path
  = link_to "Linked Services", services_feed_path
  = link_to "Subscribe", subscribe_feed_path
  = render 'forms'
  .posts
    = render @posts, feed: @feed 

app/views/feeds/not_allowed.html.haml
This feed is private.

= link_to "Ask for access", ask_for_access_feed_path(@feed.subdomain)

app/views/feeds/services.html.haml
.add
  = form_tag add_service_feed_path do 
    = label_tag :twitter_id, "Twitter id"
    = text_field_tag :twitter_id 
    = submit_tag 'Link to Twitter'

.remove
  = form_tag add_service_feed_path do 
    = label_tag :twitter_id, "Twitter id"
    = text_field_tag :twitter_id 
    = hidden_field_tag :add, false
    = submit_tag 'Unlink Twitter'

app/views/feeds/visibility.html.haml
= "Feed is #{current_feed.public? ? "public" : "private"}"
= link_to "Make private", toggle_visibility_feed_path
.granted
  = render current_feed.allowed_users
.pleads
  = render current_user.inbox.access_requests.to_a

app/views/home/index.html.haml
.home
  %h1 MEDIA FEED
  .blogs.list
    - @feeds.each do |feed|
      = link_to feed.capitalize, feed_path(feed)
      <br/>
  .copy
    %p The only site you can share your photos, links and thoughts with your friends!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FeedEngine</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>


<%= render 'session/top_bar' %>
 <%= yield %>

</body>
</html>

app/views/messages/_message.html.haml
= message.sender.nick
= message.content
= button_to "Approve", approve_access_feed_path(user_id: message.sender.id)

app/views/posts/_form.html.haml
= form_for [feed, post], url: feed_posts_path(feed.subdomain) do |f|
  .title
    = f.label :title
    = f.text_field :title
  .description
    = f.label :description
    = f.text_area :description
  .submit
    = f.submit "Submit"

app/views/posts/_photo.html.haml
=image_tag photo_url

app/views/posts/_photo_form.html.haml
= form_for [feed, post], url: feed_posts_path(feed.subdomain) do |f|
  .title
    = f.label :title
    = f.text_field :title
  .photo
    = f.label :photo
    = f.text_field :photo
  .description
    = f.label :description
    = f.text_area :description
    = f.hidden_field :type, {value: post.class}
  .submit
    = f.submit "Submit"

app/views/posts/_post.html.haml
.post
  = post.title
  = post.description
  = post.user.nick
  .content
    = post.render_content(self)
  = link_to "Points! #{post.points}", add_points_feed_post_path(feed.subdomain, post)
  = link_to "Refeed", refeed_feed_post_path(feed, post)

app/views/posts/_tweet.html.haml
.tweet
  = tweet.source
  = tweet.body

app/views/session/_notifications.html.haml
.notifications
  -if current_user.inbox.access_requests.any?
    = "Pending access requests: #{current_user.inbox.access_requests.count}" 

app/views/session/_top_bar.html.haml
-if user_signed_in?
  = "Logged as: #{current_user.nick}" 
  = render 'session/notifications'
-else
  Guest
= link_to "Sign out", destroy_user_session_path, method: :delete
= link_to "Log in", new_user_session_path

app/views/users/_user.html.haml
= user.nick

app/views/users/create.html.haml
%h1 Users#create
%p Find me in app/views/users/create.html.haml

app/views/users/destroy.html.haml
%h1 Users#destroy
%p Find me in app/views/users/destroy.html.haml

app/views/users/index.html.haml
%h1 Users#index
%p Find me in app/views/users/index.html.haml

= @users.map(&:email)

app/views/users/profile.html.haml
In user profile
= "#{@user.nick}'s profile"

app/views/users/show.html.haml
%h1 Users#show
%p Find me in app/views/users/show.html.haml
= @user.first_name
= @user.last_name
= @user.nick
= @user.email

app/views/users/update.html.haml
%h1 Users#update
%p Find me in app/views/users/update.html.haml